from typing import Protocol
import numpy as np

class Grabber(Protocol):
    def init_grabber(self, config: dict) -> None: ...
    def grab_image(self) -> np.ndarray: ...
    def close(self) -> None: ...
        