from typing import Protocol

class Uploader(Protocol):
    def upload_single_file(self, dest_path : str, file_path : str,) -> bool: ...
    def upload_multiple_files(self, dest_path : str, file_path_list : list[str]) -> bool: ...