from typing import Protocol

class Uploader(Protocol):
    def upload_single_file(self, dest_path : str, file_path : str) -> None: ...
    def upload_multiple_files(self, dest_path : str, file_path : list[str]) -> None: ...